=== noyyyd/epam-chat/src/main/XML/XSDweb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/web"
        xmlns:ths="http://www.example.com/web"
        elementFormDefault="qualified">


    <element name="web-app">
        <complexType>
            <sequence>
                <element name="display-name" type="string"/>
                <element ref="ths:users"/>
                <element ref="ths:messages"/>

            </sequence>
        </complexType>
    </element>

    <element name="messages">
        <complexType>
            <sequence>
                <element name="message"
                         type="ths:Message"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="users">
        <complexType>
            <sequence>
                <element name="user"
                         type="ths:User"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Message">
        <sequence>
            <element name="user_from" type="string"/>
            <element name="time_stamp" type="string"/>
            <element name="text" type="string"/>
            <element name="status" type="ths:Status"/>
        </sequence>
    </complexType>

    <simpleType name="Status">
        <restriction base="string">
            <enumeration value="LOGIN"/>
            <enumeration value="MESSAGE"/>
            <enumeration value="KICK"/>
            <enumeration value="LOGOUT"/>
        </restriction>
    </simpleType>

    <simpleType name="Role">
        <restriction base="string">
            <enumeration value="ADMIN"/>
            <enumeration value="USER"/>
        </restriction>
    </simpleType>

    <complexType name="User">
        <sequence>
            <element name="nick" type="string"/>
            <element name="role" type="ths:Role"/>
        </sequence>
    </complexType>
</schema>

=== noyyyd/epam-chat/src/main/XML/chat_web.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<web-app xmlns="http://www.example.com/web" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/web XSDweb.xsd">
    <display-name>Web Chat</display-name>
    <users>
        <user>
            <nick>Alexandr</nick>
            <role>ADMIN</role>
        </user>
        <user>
            <nick>Michael</nick>
            <role>USER</role>
        </user>

        <user>
            <nick>nick</nick>
            <role>USER</role>
        </user>
    </users>
    <messages>
        <message>
            <user_from>Michael</user_from>
            <time_stamp>2021-04-24 17:17:33</time_stamp>
            <text/>
            <status>LOGIN</status>
        </message>
        <message>
            <user_from>Alexandr</user_from>
            <time_stamp>2021-04-24 12:49:53</time_stamp>
            <text/>
            <status>LOGIN</status>
        </message>
        <message>
            <user_from>Alexandr</user_from>
            <time_stamp>2014-11-21 15:00:02</time_stamp>
            <text>Hi!</text>
            <status>MESSAGE</status>
        </message>
        <message>
            <user_from>Michael</user_from>
            <time_stamp>2021-04-24 12:35:49</time_stamp>
            <text>Hi, Alexandr!</text>
            <status>MESSAGE</status>
        </message>
        <message>
            <user_from>Alexandr</user_from>
            <time_stamp>2021-04-24 12:35:49</time_stamp>
            <text/>
            <status>LOGOUT</status>
        </message>
        <message>
            <user_from>Michael</user_from>
            <time_stamp>2021-04-24 12:35:49</time_stamp>
            <text/>
            <status>LOGOUT</status>
        </message>
        <message>
            <user_from>nick</user_from>
            <time_stamp>2021-04-29 22:15:33</time_stamp>
            <text>nick entered the chat</text>
            <status>LOGIN</status>
        </message>
        <message>
            <user_from>nick</user_from>
            <time_stamp>2021-05-02 18:10:06</time_stamp>
            <text>nick</text>
            <status>KICK</status>
        </message>
    </messages>
</web-app>
